
[ClassVersion("1.0.0"), FriendlyName("PVSFarmConfig")]
class CTX_PVSFarmConfig : OMI_BaseResource
{
    [Key, Description("PVS Farm name.")] String FarmName;
    [Write, Description("Description of the PVS Farm.")] String Description;
    [Write, Description("True when Auto Add is enabled, false otherwise.")] Boolean AutoAddEnabled;
    [Write, Description("True when Auditing is enabled, false otherwise.")] Boolean AuditingEnabled;
    [Write, Description("Name of the Site to place new Devices into automatically.")] String DefaultSiteName;
    [Write, Description("True when Offline Database Support is enabled, false otherwise.")] Boolean OfflineDatabaseSupportEnabled;
    [Write, Description("License server name.")] String LicenseServer;
    [Write, Description("License server port.")] UInt32 LicenseServerPort;
    [Write, Description("License server trade up, when set to true.")] Boolean LicenseTradeUp;
    [Write, Description("True when Automatic Merge is enabled, false otherwise. If the number of versions becomes more than the MaxVersions value, a merge will occur at the end of PromoteDiskVersion.")] Boolean AutomaticMergeEnabled;
    [Write, Description("Maximum number a version of a Disk that can exist before a merge will automatically occur. Min=3, Max=50.")] UInt32 MaxVersions;
    [Write, Description("Mode to place the version in after a merge has occurred. Values are: 0 (Production), 1 (Test) and 2 (Maintenance). Min=0, Max=2.")] UInt32 MergeMode;
    [Write, Description("PVS Server name to connect to. Defaults to 'localhost'.")] String PVSServerName;
    [Write, Description("SOAP port.")] UInt64 SoapPort;
    [Write, Description("Username to connect to PVS server.")] String Username;
    [Write, Description("Password to connect to PVS server"), EmbeddedInstance("MSFT_Credential")] String Password;
};
